In [ ]:
string = "Practice Problems to Drill List Comprehension in Your Head."

1.	Find all of the numbers from 1–1000 that are divisible by 8
2.	Find all of the numbers from 1–1000 that have a 6 in them
3.	Count the number of spaces in a string (use string above)
4.	Remove all of the vowels in a string (use string above)
5.	Find all of the words in a string that are less than 5 letters (use string above)
6.	Use a dictionary comprehension to count the length of each word in a sentence (use string above)
7.	Use a nested list comprehension to find all of the numbers from 1–1000 that are divisible by any single digit besides 1 (2–9)
8.	For all the numbers 1–1000, use a nested list/dictionary comprehension to find the highest single digit any of the numbers is divisible by

In [42]:
# Find all of the numbers from 1–1000 that are divisible by 8
output=[i for i in range(1,1001) if i%8==0]
print(output)

[8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 264, 272, 280, 288, 296, 304, 312, 320, 328, 336, 344, 352, 360, 368, 376, 384, 392, 400, 408, 416, 424, 432, 440, 448, 456, 464, 472, 480, 488, 496, 504, 512, 520, 528, 536, 544, 552, 560, 568, 576, 584, 592, 600, 608, 616, 624, 632, 640, 648, 656, 664, 672, 680, 688, 696, 704, 712, 720, 728, 736, 744, 752, 760, 768, 776, 784, 792, 800, 808, 816, 824, 832, 840, 848, 856, 864, 872, 880, 888, 896, 904, 912, 920, 928, 936, 944, 952, 960, 968, 976, 984, 992, 1000]

In [43]:
len(output)

125

In [44]:
#Find all of the numbers from 1–1000 that have a 6 in them
output= [i  for i in range(1,1001) if '6' in str(i)]
print(output)

[6, 16, 26, 36, 46, 56, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 76, 86, 96, 106, 116, 126, 136, 146, 156, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 176, 186, 196, 206, 216, 226, 236, 246, 256, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 276, 286, 296, 306, 316, 326, 336, 346, 356, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 376, 386, 396, 406, 416, 426, 436, 446, 456, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 476, 486, 496, 506, 516, 526, 536, 546, 556, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 576, 586, 596, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 706, 716, 726, 736, 746, 756, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 776, 786, 796, 806, 816, 826, 836, 846, 856, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 876, 886, 896, 906, 916, 926, 936, 946, 956, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 976, 986, 996]

In [45]:
len(output)

271

In [46]:
#Count the number of spaces in a string (use string above)
string = "Practice Problems to Drill List Comprehension in Your Head."
output=len([i  for i in string if i==' '])
print(output)

8

In [48]:
# Remove all of the vowels in a string (use string above)
string = "Practice Problems to Drill List Comprehension in Your Head."
output=''.join([i  for i in string if i not in 'aeiouAEIOU'])
output

'Prctc Prblms t Drll Lst Cmprhnsn n Yr Hd.'

In [49]:
# Find all of the words in a string that are less than 5 letters (use string above)
string = "Practice Problems to Drill List Comprehension in Your Head."
output=[i for i in string.split() if len(i)<5 ]
print(output)

['to', 'List', 'in', 'Your']

In [50]:
# Use a dictionary comprehension to count the length of each word in a sentence (use string above)
string = "Practice Problems to Drill List Comprehension in Your Head."
output={i:len(i) for i in string.split()}
print(output)

{'Practice': 8, 'Problems': 8, 'to': 2, 'Drill': 5, 'List': 4, 'Comprehension': 13, 'in': 2, 'Your': 4, 'Head.': 5}

In [56]:
# Use a nested list comprehension to find all of the numbers from 1–1000 that are divisible by any single digit besides 1 (2–9)
output=[i for i in range(1,1001) if True in [True for j in range(2,10) if i%j ==0]]
print(output)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 15, 16, 18, 20, 21, 22, 24, 25, 26, 27, 28, 30, 32, 33, 34, 35, 36, 38, 39, 40, 42, 44, 45, 46, 48, 49, 50, 51, 52, 54, 55, 56, 57, 58, 60, 62, 63, 64, 65, 66, 68, 69, 70, 72, 74, 75, 76, 77, 78, 80, 81, 82, 84, 85, 86, 87, 88, 90, 91, 92, 93, 94, 95, 96, 98, 99, 100, 102, 104, 105, 106, 108, 110, 111, 112, 114, 115, 116, 117, 118, 119, 120, 122, 123, 124, 125, 126, 128, 129, 130, 132, 133, 134, 135, 136, 138, 140, 141, 142, 144, 145, 146, 147, 148, 150, 152, 153, 154, 155, 156, 158, 159, 160, 161, 162, 164, 165, 166, 168, 170, 171, 172, 174, 175, 176, 177, 178, 180, 182, 183, 184, 185, 186, 188, 189, 190, 192, 194, 195, 196, 198, 200, 201, 202, 203, 204, 205, 206, 207, 208, 210, 212, 213, 214, 215, 216, 217, 218, 219, 220, 222, 224, 225, 226, 228, 230, 231, 232, 234, 235, 236, 237, 238, 240, 242, 243, 244, 245, 246, 248, 249, 250, 252, 254, 255, 256, 258, 259, 260, 261, 262, 264, 265, 266, 267, 268, 270, 272, 273, 274, 275, 276, 278, 279, 280, 282, 284, 285, 286, 287, 288, 290, 291, 292, 294, 295, 296, 297, 298, 300, 301, 302, 303, 304, 305, 306, 308, 309, 310, 312, 314, 315, 316, 318, 320, 321, 322, 324, 325, 326, 327, 328, 329, 330, 332, 333, 334, 335, 336, 338, 339, 340, 342, 343, 344, 345, 346, 348, 350, 351, 352, 354, 355, 356, 357, 358, 360, 362, 363, 364, 365, 366, 368, 369, 370, 371, 372, 374, 375, 376, 378, 380, 381, 382, 384, 385, 386, 387, 388, 390, 392, 393, 394, 395, 396, 398, 399, 400, 402, 404, 405, 406, 408, 410, 411, 412, 413, 414, 415, 416, 417, 418, 420, 422, 423, 424, 425, 426, 427, 428, 429, 430, 432, 434, 435, 436, 438, 440, 441, 442, 444, 445, 446, 447, 448, 450, 452, 453, 454, 455, 456, 458, 459, 460, 462, 464, 465, 466, 468, 469, 470, 471, 472, 474, 475, 476, 477, 478, 480, 482, 483, 484, 485, 486, 488, 489, 490, 492, 494, 495, 496, 497, 498, 500, 501, 502, 504, 505, 506, 507, 508, 510, 511, 512, 513, 514, 515, 516, 518, 519, 520, 522, 524, 525, 526, 528, 530, 531, 532, 534, 535, 536, 537, 538, 539, 540, 542, 543, 544, 545, 546, 548, 549, 550, 552, 553, 554, 555, 556, 558, 560, 561, 562, 564, 565, 566, 567, 568, 570, 572, 573, 574, 575, 576, 578, 579, 580, 581, 582, 584, 585, 586, 588, 590, 591, 592, 594, 595, 596, 597, 598, 600, 602, 603, 604, 605, 606, 608, 609, 610, 612, 614, 615, 616, 618, 620, 621, 622, 623, 624, 625, 626, 627, 628, 630, 632, 633, 634, 635, 636, 637, 638, 639, 640, 642, 644, 645, 646, 648, 650, 651, 652, 654, 655, 656, 657, 658, 660, 662, 663, 664, 665, 666, 668, 669, 670, 672, 674, 675, 676, 678, 679, 680, 681, 682, 684, 685, 686, 687, 688, 690, 692, 693, 694, 695, 696, 698, 699, 700, 702, 704, 705, 706, 707, 708, 710, 711, 712, 714, 715, 716, 717, 718, 720, 721, 722, 723, 724, 725, 726, 728, 729, 730, 732, 734, 735, 736, 738, 740, 741, 742, 744, 745, 746, 747, 748, 749, 750, 752, 753, 754, 755, 756, 758, 759, 760, 762, 763, 764, 765, 766, 768, 770, 771, 772, 774, 775, 776, 777, 778, 780, 782, 783, 784, 785, 786, 788, 789, 790, 791, 792, 794, 795, 796, 798, 800, 801, 802, 804, 805, 806, 807, 808, 810, 812, 813, 814, 815, 816, 818, 819, 820, 822, 824, 825, 826, 828, 830, 831, 832, 833, 834, 835, 836, 837, 838, 840, 842, 843, 844, 845, 846, 847, 848, 849, 850, 852, 854, 855, 856, 858, 860, 861, 862, 864, 865, 866, 867, 868, 870, 872, 873, 874, 875, 876, 878, 879, 880, 882, 884, 885, 886, 888, 889, 890, 891, 892, 894, 895, 896, 897, 898, 900, 902, 903, 904, 905, 906, 908, 909, 910, 912, 914, 915, 916, 917, 918, 920, 921, 922, 924, 925, 926, 927, 928, 930, 931, 932, 933, 934, 935, 936, 938, 939, 940, 942, 944, 945, 946, 948, 950, 951, 952, 954, 955, 956, 957, 958, 959, 960, 962, 963, 964, 965, 966, 968, 969, 970, 972, 973, 974, 975, 976, 978, 980, 981, 982, 984, 985, 986, 987, 988, 990, 992, 993, 994, 995, 996, 998, 999, 1000]

In [57]:
len(output)

772

For all the numbers 1–1000, use a nested list/dictionary comprehension to find the highest single digit any of the numbers is divisible by

In [92]:
for i in range(1,1001):
    for j in range(9,0,-1):
        if i%j==0:
            print(i,':',j)
            break

1 : 1
2 : 2
3 : 3
4 : 4
5 : 5
6 : 6
7 : 7
8 : 8
9 : 9
10 : 5
11 : 1
12 : 6
13 : 1
14 : 7
15 : 5
16 : 8
17 : 1
18 : 9
19 : 1
20 : 5
21 : 7
22 : 2
23 : 1
24 : 8
25 : 5
26 : 2
27 : 9
28 : 7
29 : 1
30 : 6
31 : 1
32 : 8
33 : 3
34 : 2
35 : 7
36 : 9
37 : 1
38 : 2
39 : 3
40 : 8
41 : 1
42 : 7
43 : 1
44 : 4
45 : 9
46 : 2
47 : 1
48 : 8
49 : 7
50 : 5
51 : 3
52 : 4
53 : 1
54 : 9
55 : 5
56 : 8
57 : 3
58 : 2
59 : 1
60 : 6
61 : 1
62 : 2
63 : 9
64 : 8
65 : 5
66 : 6
67 : 1
68 : 4
69 : 3
70 : 7
71 : 1
72 : 9
73 : 1
74 : 2
75 : 5
76 : 4
77 : 7
78 : 6
79 : 1
80 : 8
81 : 9
82 : 2
83 : 1
84 : 7
85 : 5
86 : 2
87 : 3
88 : 8
89 : 1
90 : 9
91 : 7
92 : 4
93 : 3
94 : 2
95 : 5
96 : 8
97 : 1
98 : 7
99 : 9
100 : 5
101 : 1
102 : 6
103 : 1
104 : 8
105 : 7
106 : 2
107 : 1
108 : 9
109 : 1
110 : 5
111 : 3
112 : 8
113 : 1
114 : 6
115 : 5
116 : 4
117 : 9
118 : 2
119 : 7
120 : 8
121 : 1
122 : 2
123 : 3
124 : 4
125 : 5
126 : 9
127 : 1
128 : 8
129 : 3
130 : 5
131 : 1
132 : 6
133 : 7
134 : 2
135 : 9
136 : 8
137 : 1
138 : 6
139 : 1
140 : 7
141 : 3
142 : 2
143 : 1
144 : 9
145 : 5
146 : 2
147 : 7
148 : 4
149 : 1
150 : 6
151 : 1
152 : 8
153 : 9
154 : 7
155 : 5
156 : 6
157 : 1
158 : 2
159 : 3
160 : 8
161 : 7
162 : 9
163 : 1
164 : 4
165 : 5
166 : 2
167 : 1
168 : 8
169 : 1
170 : 5
171 : 9
172 : 4
173 : 1
174 : 6
175 : 7
176 : 8
177 : 3
178 : 2
179 : 1
180 : 9
181 : 1
182 : 7
183 : 3
184 : 8
185 : 5
186 : 6
187 : 1
188 : 4
189 : 9
190 : 5
191 : 1
192 : 8
193 : 1
194 : 2
195 : 5
196 : 7
197 : 1
198 : 9
199 : 1
200 : 8
201 : 3
202 : 2
203 : 7
204 : 6
205 : 5
206 : 2
207 : 9
208 : 8
209 : 1
210 : 7
211 : 1
212 : 4
213 : 3
214 : 2
215 : 5
216 : 9
217 : 7
218 : 2
219 : 3
220 : 5
221 : 1
222 : 6
223 : 1
224 : 8
225 : 9
226 : 2
227 : 1
228 : 6
229 : 1
230 : 5
231 : 7
232 : 8
233 : 1
234 : 9
235 : 5
236 : 4
237 : 3
238 : 7
239 : 1
240 : 8
241 : 1
242 : 2
243 : 9
244 : 4
245 : 7
246 : 6
247 : 1
248 : 8
249 : 3
250 : 5
251 : 1
252 : 9
253 : 1
254 : 2
255 : 5
256 : 8
257 : 1
258 : 6
259 : 7
260 : 5
261 : 9
262 : 2
263 : 1
264 : 8
265 : 5
266 : 7
267 : 3
268 : 4
269 : 1
270 : 9
271 : 1
272 : 8
273 : 7
274 : 2
275 : 5
276 : 6
277 : 1
278 : 2
279 : 9
280 : 8
281 : 1
282 : 6
283 : 1
284 : 4
285 : 5
286 : 2
287 : 7
288 : 9
289 : 1
290 : 5
291 : 3
292 : 4
293 : 1
294 : 7
295 : 5
296 : 8
297 : 9
298 : 2
299 : 1
300 : 6
301 : 7
302 : 2
303 : 3
304 : 8
305 : 5
306 : 9
307 : 1
308 : 7
309 : 3
310 : 5
311 : 1
312 : 8
313 : 1
314 : 2
315 : 9
316 : 4
317 : 1
318 : 6
319 : 1
320 : 8
321 : 3
322 : 7
323 : 1
324 : 9
325 : 5
326 : 2
327 : 3
328 : 8
329 : 7
330 : 6
331 : 1
332 : 4
333 : 9
334 : 2
335 : 5
336 : 8
337 : 1
338 : 2
339 : 3
340 : 5
341 : 1
342 : 9
343 : 7
344 : 8
345 : 5
346 : 2
347 : 1
348 : 6
349 : 1
350 : 7
351 : 9
352 : 8
353 : 1
354 : 6
355 : 5
356 : 4
357 : 7
358 : 2
359 : 1
360 : 9
361 : 1
362 : 2
363 : 3
364 : 7
365 : 5
366 : 6
367 : 1
368 : 8
369 : 9
370 : 5
371 : 7
372 : 6
373 : 1
374 : 2
375 : 5
376 : 8
377 : 1
378 : 9
379 : 1
380 : 5
381 : 3
382 : 2
383 : 1
384 : 8
385 : 7
386 : 2
387 : 9
388 : 4
389 : 1
390 : 6
391 : 1
392 : 8
393 : 3
394 : 2
395 : 5
396 : 9
397 : 1
398 : 2
399 : 7
400 : 8
401 : 1
402 : 6
403 : 1
404 : 4
405 : 9
406 : 7
407 : 1
408 : 8
409 : 1
410 : 5
411 : 3
412 : 4
413 : 7
414 : 9
415 : 5
416 : 8
417 : 3
418 : 2
419 : 1
420 : 7
421 : 1
422 : 2
423 : 9
424 : 8
425 : 5
426 : 6
427 : 7
428 : 4
429 : 3
430 : 5
431 : 1
432 : 9
433 : 1
434 : 7
435 : 5
436 : 4
437 : 1
438 : 6
439 : 1
440 : 8
441 : 9
442 : 2
443 : 1
444 : 6
445 : 5
446 : 2
447 : 3
448 : 8
449 : 1
450 : 9
451 : 1
452 : 4
453 : 3
454 : 2
455 : 7
456 : 8
457 : 1
458 : 2
459 : 9
460 : 5
461 : 1
462 : 7
463 : 1
464 : 8
465 : 5
466 : 2
467 : 1
468 : 9
469 : 7
470 : 5
471 : 3
472 : 8
473 : 1
474 : 6
475 : 5
476 : 7
477 : 9
478 : 2
479 : 1
480 : 8
481 : 1
482 : 2
483 : 7
484 : 4
485 : 5
486 : 9
487 : 1
488 : 8
489 : 3
490 : 7
491 : 1
492 : 6
493 : 1
494 : 2
495 : 9
496 : 8
497 : 7
498 : 6
499 : 1
500 : 5
501 : 3
502 : 2
503 : 1
504 : 9
505 : 5
506 : 2
507 : 3
508 : 4
509 : 1
510 : 6
511 : 7
512 : 8
513 : 9
514 : 2
515 : 5
516 : 6
517 : 1
518 : 7
519 : 3
520 : 8
521 : 1
522 : 9
523 : 1
524 : 4
525 : 7
526 : 2
527 : 1
528 : 8
529 : 1
530 : 5
531 : 9
532 : 7
533 : 1
534 : 6
535 : 5
536 : 8
537 : 3
538 : 2
539 : 7
540 : 9
541 : 1
542 : 2
543 : 3
544 : 8
545 : 5
546 : 7
547 : 1
548 : 4
549 : 9
550 : 5
551 : 1
552 : 8
553 : 7
554 : 2
555 : 5
556 : 4
557 : 1
558 : 9
559 : 1
560 : 8
561 : 3
562 : 2
563 : 1
564 : 6
565 : 5
566 : 2
567 : 9
568 : 8
569 : 1
570 : 6
571 : 1
572 : 4
573 : 3
574 : 7
575 : 5
576 : 9
577 : 1
578 : 2
579 : 3
580 : 5
581 : 7
582 : 6
583 : 1
584 : 8
585 : 9
586 : 2
587 : 1
588 : 7
589 : 1
590 : 5
591 : 3
592 : 8
593 : 1
594 : 9
595 : 7
596 : 4
597 : 3
598 : 2
599 : 1
600 : 8
601 : 1
602 : 7
603 : 9
604 : 4
605 : 5
606 : 6
607 : 1
608 : 8
609 : 7
610 : 5
611 : 1
612 : 9
613 : 1
614 : 2
615 : 5
616 : 8
617 : 1
618 : 6
619 : 1
620 : 5
621 : 9
622 : 2
623 : 7
624 : 8
625 : 5
626 : 2
627 : 3
628 : 4
629 : 1
630 : 9
631 : 1
632 : 8
633 : 3
634 : 2
635 : 5
636 : 6
637 : 7
638 : 2
639 : 9
640 : 8
641 : 1
642 : 6
643 : 1
644 : 7
645 : 5
646 : 2
647 : 1
648 : 9
649 : 1
650 : 5
651 : 7
652 : 4
653 : 1
654 : 6
655 : 5
656 : 8
657 : 9
658 : 7
659 : 1
660 : 6
661 : 1
662 : 2
663 : 3
664 : 8
665 : 7
666 : 9
667 : 1
668 : 4
669 : 3
670 : 5
671 : 1
672 : 8
673 : 1
674 : 2
675 : 9
676 : 4
677 : 1
678 : 6
679 : 7
680 : 8
681 : 3
682 : 2
683 : 1
684 : 9
685 : 5
686 : 7
687 : 3
688 : 8
689 : 1
690 : 6
691 : 1
692 : 4
693 : 9
694 : 2
695 : 5
696 : 8
697 : 1
698 : 2
699 : 3
700 : 7
701 : 1
702 : 9
703 : 1
704 : 8
705 : 5
706 : 2
707 : 7
708 : 6
709 : 1
710 : 5
711 : 9
712 : 8
713 : 1
714 : 7
715 : 5
716 : 4
717 : 3
718 : 2
719 : 1
720 : 9
721 : 7
722 : 2
723 : 3
724 : 4
725 : 5
726 : 6
727 : 1
728 : 8
729 : 9
730 : 5
731 : 1
732 : 6
733 : 1
734 : 2
735 : 7
736 : 8
737 : 1
738 : 9
739 : 1
740 : 5
741 : 3
742 : 7
743 : 1
744 : 8
745 : 5
746 : 2
747 : 9
748 : 4
749 : 7
750 : 6
751 : 1
752 : 8
753 : 3
754 : 2
755 : 5
756 : 9
757 : 1
758 : 2
759 : 3
760 : 8
761 : 1
762 : 6
763 : 7
764 : 4
765 : 9
766 : 2
767 : 1
768 : 8
769 : 1
770 : 7
771 : 3
772 : 4
773 : 1
774 : 9
775 : 5
776 : 8
777 : 7
778 : 2
779 : 1
780 : 6
781 : 1
782 : 2
783 : 9
784 : 8
785 : 5
786 : 6
787 : 1
788 : 4
789 : 3
790 : 5
791 : 7
792 : 9
793 : 1
794 : 2
795 : 5
796 : 4
797 : 1
798 : 7
799 : 1
800 : 8
801 : 9
802 : 2
803 : 1
804 : 6
805 : 7
806 : 2
807 : 3
808 : 8
809 : 1
810 : 9
811 : 1
812 : 7
813 : 3
814 : 2
815 : 5
816 : 8
817 : 1
818 : 2
819 : 9
820 : 5
821 : 1
822 : 6
823 : 1
824 : 8
825 : 5
826 : 7
827 : 1
828 : 9
829 : 1
830 : 5
831 : 3
832 : 8
833 : 7
834 : 6
835 : 5
836 : 4
837 : 9
838 : 2
839 : 1
840 : 8
841 : 1
842 : 2
843 : 3
844 : 4
845 : 5
846 : 9
847 : 7
848 : 8
849 : 3
850 : 5
851 : 1
852 : 6
853 : 1
854 : 7
855 : 9
856 : 8
857 : 1
858 : 6
859 : 1
860 : 5
861 : 7
862 : 2
863 : 1
864 : 9
865 : 5
866 : 2
867 : 3
868 : 7
869 : 1
870 : 6
871 : 1
872 : 8
873 : 9
874 : 2
875 : 7
876 : 6
877 : 1
878 : 2
879 : 3
880 : 8
881 : 1
882 : 9
883 : 1
884 : 4
885 : 5
886 : 2
887 : 1
888 : 8
889 : 7
890 : 5
891 : 9
892 : 4
893 : 1
894 : 6
895 : 5
896 : 8
897 : 3
898 : 2
899 : 1
900 : 9
901 : 1
902 : 2
903 : 7
904 : 8
905 : 5
906 : 6
907 : 1
908 : 4
909 : 9
910 : 7
911 : 1
912 : 8
913 : 1
914 : 2
915 : 5
916 : 4
917 : 7
918 : 9
919 : 1
920 : 8
921 : 3
922 : 2
923 : 1
924 : 7
925 : 5
926 : 2
927 : 9
928 : 8
929 : 1
930 : 6
931 : 7
932 : 4
933 : 3
934 : 2
935 : 5
936 : 9
937 : 1
938 : 7
939 : 3
940 : 5
941 : 1
942 : 6
943 : 1
944 : 8
945 : 9
946 : 2
947 : 1
948 : 6
949 : 1
950 : 5
951 : 3
952 : 8
953 : 1
954 : 9
955 : 5
956 : 4
957 : 3
958 : 2
959 : 7
960 : 8
961 : 1
962 : 2
963 : 9
964 : 4
965 : 5
966 : 7
967 : 1
968 : 8
969 : 3
970 : 5
971 : 1
972 : 9
973 : 7
974 : 2
975 : 5
976 : 8
977 : 1
978 : 6
979 : 1
980 : 7
981 : 9
982 : 2
983 : 1
984 : 8
985 : 5
986 : 2
987 : 7
988 : 4
989 : 1
990 : 9
991 : 1
992 : 8
993 : 3
994 : 7
995 : 5
996 : 6
997 : 1
998 : 2
999 : 9
1000 : 8

In [90]:
print({i:max([j for j in range(1,10) if i%j==0]) for i in range(1,1001)})

{1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 5, 11: 1, 12: 6, 13: 1, 14: 7, 15: 5, 16: 8, 17: 1, 18: 9, 19: 1, 20: 5, 21: 7, 22: 2, 23: 1, 24: 8, 25: 5, 26: 2, 27: 9, 28: 7, 29: 1, 30: 6, 31: 1, 32: 8, 33: 3, 34: 2, 35: 7, 36: 9, 37: 1, 38: 2, 39: 3, 40: 8, 41: 1, 42: 7, 43: 1, 44: 4, 45: 9, 46: 2, 47: 1, 48: 8, 49: 7, 50: 5, 51: 3, 52: 4, 53: 1, 54: 9, 55: 5, 56: 8, 57: 3, 58: 2, 59: 1, 60: 6, 61: 1, 62: 2, 63: 9, 64: 8, 65: 5, 66: 6, 67: 1, 68: 4, 69: 3, 70: 7, 71: 1, 72: 9, 73: 1, 74: 2, 75: 5, 76: 4, 77: 7, 78: 6, 79: 1, 80: 8, 81: 9, 82: 2, 83: 1, 84: 7, 85: 5, 86: 2, 87: 3, 88: 8, 89: 1, 90: 9, 91: 7, 92: 4, 93: 3, 94: 2, 95: 5, 96: 8, 97: 1, 98: 7, 99: 9, 100: 5, 101: 1, 102: 6, 103: 1, 104: 8, 105: 7, 106: 2, 107: 1, 108: 9, 109: 1, 110: 5, 111: 3, 112: 8, 113: 1, 114: 6, 115: 5, 116: 4, 117: 9, 118: 2, 119: 7, 120: 8, 121: 1, 122: 2, 123: 3, 124: 4, 125: 5, 126: 9, 127: 1, 128: 8, 129: 3, 130: 5, 131: 1, 132: 6, 133: 7, 134: 2, 135: 9, 136: 8, 137: 1, 138: 6, 139: 1, 140: 7, 141: 3, 142: 2, 143: 1, 144: 9, 145: 5, 146: 2, 147: 7, 148: 4, 149: 1, 150: 6, 151: 1, 152: 8, 153: 9, 154: 7, 155: 5, 156: 6, 157: 1, 158: 2, 159: 3, 160: 8, 161: 7, 162: 9, 163: 1, 164: 4, 165: 5, 166: 2, 167: 1, 168: 8, 169: 1, 170: 5, 171: 9, 172: 4, 173: 1, 174: 6, 175: 7, 176: 8, 177: 3, 178: 2, 179: 1, 180: 9, 181: 1, 182: 7, 183: 3, 184: 8, 185: 5, 186: 6, 187: 1, 188: 4, 189: 9, 190: 5, 191: 1, 192: 8, 193: 1, 194: 2, 195: 5, 196: 7, 197: 1, 198: 9, 199: 1, 200: 8, 201: 3, 202: 2, 203: 7, 204: 6, 205: 5, 206: 2, 207: 9, 208: 8, 209: 1, 210: 7, 211: 1, 212: 4, 213: 3, 214: 2, 215: 5, 216: 9, 217: 7, 218: 2, 219: 3, 220: 5, 221: 1, 222: 6, 223: 1, 224: 8, 225: 9, 226: 2, 227: 1, 228: 6, 229: 1, 230: 5, 231: 7, 232: 8, 233: 1, 234: 9, 235: 5, 236: 4, 237: 3, 238: 7, 239: 1, 240: 8, 241: 1, 242: 2, 243: 9, 244: 4, 245: 7, 246: 6, 247: 1, 248: 8, 249: 3, 250: 5, 251: 1, 252: 9, 253: 1, 254: 2, 255: 5, 256: 8, 257: 1, 258: 6, 259: 7, 260: 5, 261: 9, 262: 2, 263: 1, 264: 8, 265: 5, 266: 7, 267: 3, 268: 4, 269: 1, 270: 9, 271: 1, 272: 8, 273: 7, 274: 2, 275: 5, 276: 6, 277: 1, 278: 2, 279: 9, 280: 8, 281: 1, 282: 6, 283: 1, 284: 4, 285: 5, 286: 2, 287: 7, 288: 9, 289: 1, 290: 5, 291: 3, 292: 4, 293: 1, 294: 7, 295: 5, 296: 8, 297: 9, 298: 2, 299: 1, 300: 6, 301: 7, 302: 2, 303: 3, 304: 8, 305: 5, 306: 9, 307: 1, 308: 7, 309: 3, 310: 5, 311: 1, 312: 8, 313: 1, 314: 2, 315: 9, 316: 4, 317: 1, 318: 6, 319: 1, 320: 8, 321: 3, 322: 7, 323: 1, 324: 9, 325: 5, 326: 2, 327: 3, 328: 8, 329: 7, 330: 6, 331: 1, 332: 4, 333: 9, 334: 2, 335: 5, 336: 8, 337: 1, 338: 2, 339: 3, 340: 5, 341: 1, 342: 9, 343: 7, 344: 8, 345: 5, 346: 2, 347: 1, 348: 6, 349: 1, 350: 7, 351: 9, 352: 8, 353: 1, 354: 6, 355: 5, 356: 4, 357: 7, 358: 2, 359: 1, 360: 9, 361: 1, 362: 2, 363: 3, 364: 7, 365: 5, 366: 6, 367: 1, 368: 8, 369: 9, 370: 5, 371: 7, 372: 6, 373: 1, 374: 2, 375: 5, 376: 8, 377: 1, 378: 9, 379: 1, 380: 5, 381: 3, 382: 2, 383: 1, 384: 8, 385: 7, 386: 2, 387: 9, 388: 4, 389: 1, 390: 6, 391: 1, 392: 8, 393: 3, 394: 2, 395: 5, 396: 9, 397: 1, 398: 2, 399: 7, 400: 8, 401: 1, 402: 6, 403: 1, 404: 4, 405: 9, 406: 7, 407: 1, 408: 8, 409: 1, 410: 5, 411: 3, 412: 4, 413: 7, 414: 9, 415: 5, 416: 8, 417: 3, 418: 2, 419: 1, 420: 7, 421: 1, 422: 2, 423: 9, 424: 8, 425: 5, 426: 6, 427: 7, 428: 4, 429: 3, 430: 5, 431: 1, 432: 9, 433: 1, 434: 7, 435: 5, 436: 4, 437: 1, 438: 6, 439: 1, 440: 8, 441: 9, 442: 2, 443: 1, 444: 6, 445: 5, 446: 2, 447: 3, 448: 8, 449: 1, 450: 9, 451: 1, 452: 4, 453: 3, 454: 2, 455: 7, 456: 8, 457: 1, 458: 2, 459: 9, 460: 5, 461: 1, 462: 7, 463: 1, 464: 8, 465: 5, 466: 2, 467: 1, 468: 9, 469: 7, 470: 5, 471: 3, 472: 8, 473: 1, 474: 6, 475: 5, 476: 7, 477: 9, 478: 2, 479: 1, 480: 8, 481: 1, 482: 2, 483: 7, 484: 4, 485: 5, 486: 9, 487: 1, 488: 8, 489: 3, 490: 7, 491: 1, 492: 6, 493: 1, 494: 2, 495: 9, 496: 8, 497: 7, 498: 6, 499: 1, 500: 5, 501: 3, 502: 2, 503: 1, 504: 9, 505: 5, 506: 2, 507: 3, 508: 4, 509: 1, 510: 6, 511: 7, 512: 8, 513: 9, 514: 2, 515: 5, 516: 6, 517: 1, 518: 7, 519: 3, 520: 8, 521: 1, 522: 9, 523: 1, 524: 4, 525: 7, 526: 2, 527: 1, 528: 8, 529: 1, 530: 5, 531: 9, 532: 7, 533: 1, 534: 6, 535: 5, 536: 8, 537: 3, 538: 2, 539: 7, 540: 9, 541: 1, 542: 2, 543: 3, 544: 8, 545: 5, 546: 7, 547: 1, 548: 4, 549: 9, 550: 5, 551: 1, 552: 8, 553: 7, 554: 2, 555: 5, 556: 4, 557: 1, 558: 9, 559: 1, 560: 8, 561: 3, 562: 2, 563: 1, 564: 6, 565: 5, 566: 2, 567: 9, 568: 8, 569: 1, 570: 6, 571: 1, 572: 4, 573: 3, 574: 7, 575: 5, 576: 9, 577: 1, 578: 2, 579: 3, 580: 5, 581: 7, 582: 6, 583: 1, 584: 8, 585: 9, 586: 2, 587: 1, 588: 7, 589: 1, 590: 5, 591: 3, 592: 8, 593: 1, 594: 9, 595: 7, 596: 4, 597: 3, 598: 2, 599: 1, 600: 8, 601: 1, 602: 7, 603: 9, 604: 4, 605: 5, 606: 6, 607: 1, 608: 8, 609: 7, 610: 5, 611: 1, 612: 9, 613: 1, 614: 2, 615: 5, 616: 8, 617: 1, 618: 6, 619: 1, 620: 5, 621: 9, 622: 2, 623: 7, 624: 8, 625: 5, 626: 2, 627: 3, 628: 4, 629: 1, 630: 9, 631: 1, 632: 8, 633: 3, 634: 2, 635: 5, 636: 6, 637: 7, 638: 2, 639: 9, 640: 8, 641: 1, 642: 6, 643: 1, 644: 7, 645: 5, 646: 2, 647: 1, 648: 9, 649: 1, 650: 5, 651: 7, 652: 4, 653: 1, 654: 6, 655: 5, 656: 8, 657: 9, 658: 7, 659: 1, 660: 6, 661: 1, 662: 2, 663: 3, 664: 8, 665: 7, 666: 9, 667: 1, 668: 4, 669: 3, 670: 5, 671: 1, 672: 8, 673: 1, 674: 2, 675: 9, 676: 4, 677: 1, 678: 6, 679: 7, 680: 8, 681: 3, 682: 2, 683: 1, 684: 9, 685: 5, 686: 7, 687: 3, 688: 8, 689: 1, 690: 6, 691: 1, 692: 4, 693: 9, 694: 2, 695: 5, 696: 8, 697: 1, 698: 2, 699: 3, 700: 7, 701: 1, 702: 9, 703: 1, 704: 8, 705: 5, 706: 2, 707: 7, 708: 6, 709: 1, 710: 5, 711: 9, 712: 8, 713: 1, 714: 7, 715: 5, 716: 4, 717: 3, 718: 2, 719: 1, 720: 9, 721: 7, 722: 2, 723: 3, 724: 4, 725: 5, 726: 6, 727: 1, 728: 8, 729: 9, 730: 5, 731: 1, 732: 6, 733: 1, 734: 2, 735: 7, 736: 8, 737: 1, 738: 9, 739: 1, 740: 5, 741: 3, 742: 7, 743: 1, 744: 8, 745: 5, 746: 2, 747: 9, 748: 4, 749: 7, 750: 6, 751: 1, 752: 8, 753: 3, 754: 2, 755: 5, 756: 9, 757: 1, 758: 2, 759: 3, 760: 8, 761: 1, 762: 6, 763: 7, 764: 4, 765: 9, 766: 2, 767: 1, 768: 8, 769: 1, 770: 7, 771: 3, 772: 4, 773: 1, 774: 9, 775: 5, 776: 8, 777: 7, 778: 2, 779: 1, 780: 6, 781: 1, 782: 2, 783: 9, 784: 8, 785: 5, 786: 6, 787: 1, 788: 4, 789: 3, 790: 5, 791: 7, 792: 9, 793: 1, 794: 2, 795: 5, 796: 4, 797: 1, 798: 7, 799: 1, 800: 8, 801: 9, 802: 2, 803: 1, 804: 6, 805: 7, 806: 2, 807: 3, 808: 8, 809: 1, 810: 9, 811: 1, 812: 7, 813: 3, 814: 2, 815: 5, 816: 8, 817: 1, 818: 2, 819: 9, 820: 5, 821: 1, 822: 6, 823: 1, 824: 8, 825: 5, 826: 7, 827: 1, 828: 9, 829: 1, 830: 5, 831: 3, 832: 8, 833: 7, 834: 6, 835: 5, 836: 4, 837: 9, 838: 2, 839: 1, 840: 8, 841: 1, 842: 2, 843: 3, 844: 4, 845: 5, 846: 9, 847: 7, 848: 8, 849: 3, 850: 5, 851: 1, 852: 6, 853: 1, 854: 7, 855: 9, 856: 8, 857: 1, 858: 6, 859: 1, 860: 5, 861: 7, 862: 2, 863: 1, 864: 9, 865: 5, 866: 2, 867: 3, 868: 7, 869: 1, 870: 6, 871: 1, 872: 8, 873: 9, 874: 2, 875: 7, 876: 6, 877: 1, 878: 2, 879: 3, 880: 8, 881: 1, 882: 9, 883: 1, 884: 4, 885: 5, 886: 2, 887: 1, 888: 8, 889: 7, 890: 5, 891: 9, 892: 4, 893: 1, 894: 6, 895: 5, 896: 8, 897: 3, 898: 2, 899: 1, 900: 9, 901: 1, 902: 2, 903: 7, 904: 8, 905: 5, 906: 6, 907: 1, 908: 4, 909: 9, 910: 7, 911: 1, 912: 8, 913: 1, 914: 2, 915: 5, 916: 4, 917: 7, 918: 9, 919: 1, 920: 8, 921: 3, 922: 2, 923: 1, 924: 7, 925: 5, 926: 2, 927: 9, 928: 8, 929: 1, 930: 6, 931: 7, 932: 4, 933: 3, 934: 2, 935: 5, 936: 9, 937: 1, 938: 7, 939: 3, 940: 5, 941: 1, 942: 6, 943: 1, 944: 8, 945: 9, 946: 2, 947: 1, 948: 6, 949: 1, 950: 5, 951: 3, 952: 8, 953: 1, 954: 9, 955: 5, 956: 4, 957: 3, 958: 2, 959: 7, 960: 8, 961: 1, 962: 2, 963: 9, 964: 4, 965: 5, 966: 7, 967: 1, 968: 8, 969: 3, 970: 5, 971: 1, 972: 9, 973: 7, 974: 2, 975: 5, 976: 8, 977: 1, 978: 6, 979: 1, 980: 7, 981: 9, 982: 2, 983: 1, 984: 8, 985: 5, 986: 2, 987: 7, 988: 4, 989: 1, 990: 9, 991: 1, 992: 8, 993: 3, 994: 7, 995: 5, 996: 6, 997: 1, 998: 2, 999: 9, 1000: 8}

#### Write a Program where ever there is a even number i want to print it as -1 where every there is a odd number i want to print as it is

In [95]:
import numpy as np
num=np.array([0,21,32,12,44,45,26,28,38,34,65,48,76])
new_lis=[]
for i in num:
    if i%2==0:
        new_lis.append(-1)
    else:
        new_lis.append(i)
print(new_lis)

[-1, 21, -1, -1, -1, 45, -1, -1, -1, -1, 65, -1, -1]

In [97]:
num=np.array([0,21,32,12,44,45,26,28,38,34,65,48,76])

[-1 if i%2==0 else i for i in num]

[-1, 21, -1, -1, -1, 45, -1, -1, -1, -1, 65, -1, -1]

## Lambda Exercise

In [ ]:
# 3. Write a Python program to sort a list of tuples using Lambda.
# Original list of tuples:
# [('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)]
# Sorting the List of Tuples:
# [('Social sciences', 82), ('English', 88), ('Science', 90), ('Maths', 97)]

In [2]:
a=[('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)]
a.sort(key=lambda x:x[1])
a

[('Social sciences', 82), ('English', 88), ('Science', 90), ('Maths', 97)]

In [ ]:
# 4. Write a Python program to sort a list of dictionaries using Lambda. Go to the editor
# Original list of dictionaries : sort based on color
# [{'make': 'Nokia', 'model': 216, 'color': 'Black'}, {'make': 'Mi Max', 'model': '2', 'color': 'Gold'}, {'make': 'Samsung', 'model': 7, 'color': 'Blue'}]
# Sorting the List of dictionaries :
# [{'make': 'Nokia', 'model': 216, 'color': 'Black'}, {'make': 'Samsung', 'model': 7, 'color': 'Blue'}, {'make': 'Mi Max', 'model': '2', 'color': 'Gold'}]

In [3]:
data=[{'make': 'Nokia', 'model': 216, 'color': 'Black'}, {'make': 'Mi Max', 'model': '2', 'color': 'Gold'}, {'make': 'Samsung', 'model': 7, 'color': 'Blue'}]
data.sort(key=lambda x:x['color'])
data

[{'make': 'Nokia', 'model': 216, 'color': 'Black'},
 {'make': 'Samsung', 'model': 7, 'color': 'Blue'},
 {'make': 'Mi Max', 'model': '2', 'color': 'Gold'}]

In [ ]:
# 5. Write a Python program to filter a list of integers using Lambda. Go to the editor
# Original list of integers:
# [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# Even numbers from the said list:
# [2, 4, 6, 8, 10]
# Odd numbers from the said list:
# [1, 3, 5, 7, 9]

In [4]:
data=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even=list(filter(lambda x:x%2==0,data))
odd=list(filter(lambda x:x%2!=0,data))
print(f'Even :- {even}')
print(f'Odd :- {odd}')

Even :- [2, 4, 6, 8, 10]
Odd :- [1, 3, 5, 7, 9]

In [ ]:
# 6. Write a Python program to square and cube every number in a given list of integers using Lambda. Go to the editor
# Original list of integers:
# [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# Square every number of the said list:
# [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
# Cube every number of the said list:
# [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [5]:
data=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
square=list(map(lambda x:x**2,data))
cube=list(map(lambda x:x**3,data))
print(f'Square :- {square}')
print(f'Cube :- {cube}')

Square :- [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
Cube :- [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [ ]:
# 7. Write a Python program to find if a given string starts with a given character using Lambda. Go to the editor
# Sample Output:
# True
# False

In [13]:
a=input('Enter the string')
output= lambda x: True  if x[0].startswith('P') else False
print(output(a))

Enter the stringPython
True

In [15]:
data='Python'
[True  if data[0].startswith('P')  else False]

[True]

In [ ]:
# 8. Write a Python program to extract year, month, date and time using Lambda. Go to the editor
# Sample Output:
# 2020-01-15 09:03:32.744178
# 2020
# 1
# 15
# 09:03:32.744178

In [23]:
import datetime as dt

dates=dt.datetime.now()
year=dates.year
year

2022

In [29]:
year=lambda x:x.year
month=lambda x:x.month
date=lambda x:x.day
time=lambda x:x.time()
minute=lambda x:x.minute
sec=lambda x:x.second

In [30]:
print(year(dates))
print(month(dates))
print(time(dates))
print(minute(dates))
print(sec(dates))

2022
8
07:11:22.510761
11
22

In [31]:
# 9. Write a Python program to check whether a given string is number or not using Lambda. Go to the editor
# data='-24587.11'
# Sample Output:
# True
# True
# False
# True
# False
# True
# Print checking numbers:
# True
# True

In [42]:
data='-24587.11'
inp=lambda x: x.replace('.','').isdigit()
inpu=lambda a: inp(a[1:]) if a[0]=='-' else inp(a)
inpu(data)

True

In [44]:
user=input('Enter the number')
input1= lambda x:x.replace('.','').isdigit() 
input2= lambda b: input1(b[1:])   if b[0]=='-' else input1(b)
input2(user)

Enter the number-253.36

True

In [ ]:
# 10. Write a Python program to create Fibonacci series upto n using Lambda. Go to the editor
# Fibonacci series upto 2:
# [0, 1]
# Fibonacci series upto 5:
# [0, 1, 1, 2, 3]
# Fibonacci series upto 6:
# [0, 1, 1, 2, 3, 5]
# Fibonacci series upto 9:
# [0, 1, 1, 2, 3, 5, 8, 13, 21]

In [46]:
def fibonacci(n):
    output=[]
    a=0
    b=1
    if n==0:
        output.append(a)
    else:
        output.append(a)
        output.append(b)
        for i in range(n-2):
            c=a+b
            a=b
            b=c
            output.append(c)
    print(output)
fibonacci(5)

[0, 1, 1, 2, 3]

In [ ]:
# 11. Write a Python program to find intersection of two given arrays using Lambda. Go to the editor
# Original arrays:
# [1, 2, 3, 5, 7, 8, 9, 10]
# [1, 2, 4, 8, 9]
# Intersection of the said arrays: [1, 2, 8, 9]

In [53]:
a=[1, 2, 3, 5, 7, 8, 9, 10]
b=[1, 2, 4, 8, 9]
output=list(set(a).intersection(set(b)))
print(output)

output1=list(filter(lambda x: x in b,a))
print(output)

[8, 1, 2, 9]
[8, 1, 2, 9]

In [ ]:
# 12. Write a Python program to rearrange positive and negative numbers in a given array using Lambda. Go to the editor
# Original arrays:
# [-1, 2, -3, 5, 7, 8, 9, -10]
# Rearrange positive and negative numbers of the said array:
# [2, 5, 7, 8, 9, -10, -3, -1]

In [55]:
data=[-1, 2, -3, 5, 7, 8, 9, -10]
data.sort()
data

[-10, -3, -1, 2, 5, 7, 8, 9]

In [60]:
data=[-1, 2, -3, 5, 7, 8, 9, -10]
sorted(data,key=lambda x:x if x==0 else -1/x)

[2, 5, 7, 8, 9, -10, -3, -1]

In [ ]:
# 13. Write a Python program to count the even, odd numbers in a given array of integers using Lambda. Go to the editor
# Original arrays:
# [1, 2, 3, 5, 7, 8, 9, 10]
# Number of even numbers in the above array: 3
# Number of odd numbers in the above array: 5

In [69]:
data=[1, 2, 3, 5, 7, 8, 9, 10]
even_numbers= len(list(filter(lambda x:x%2==0,data)))
odd_numbers= len(list(filter(lambda x:x%2!=0,data)))
print(f'Number of Even Numbers in the above array :{even_numbers}')
print(f'Number of Even Numbers in the above array :{odd_numbers}')

Number of Even Numbers in the above array :3
Number of Even Numbers in the above array :5

In [ ]:
# 14. Write a Python program to find the values of length six in a given list using Lambda. Go to the editor
# Sample Output:
# Monday
# Friday
# Sunday

In [71]:
weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
list(filter(lambda x:len(x)==6,weekdays))

['Monday', 'Friday', 'Sunday']

In [ ]:
# 15. Write a Python program to add two given lists using map and lambda. Go to the editor
# Original list:
# [1, 2, 3]
# [4, 5, 6]
# Result: after adding two list
# [5, 7, 9]

In [80]:
a=[1,2,3]
b=[4,5,6]
output=list(map(lambda x,y:x+y,a,b))
print(output)

[5, 7, 9]

In [ ]:
# 17. Write a Python program to find numbers divisible by nineteen or thirteen from a list of numbers using Lambda. Go to the editor
# Orginal list:
# [19, 65, 57, 39, 152, 639, 121, 44, 90, 190]
# Numbers of the above list divisible by nineteen or thirteen:
# [19, 65, 57, 39, 152, 190]

In [89]:
a=[19, 65, 57, 39, 152, 639, 121, 44, 90, 190]
list(filter(lambda x:x if x%19==0 or x%13==0 else '',a))

[19, 65, 57, 39, 152, 190]

In [ ]:
# 18. Write a Python program to find palindromes in a given list of strings using Lambda. Go to the editor
# Orginal list of strings:
# ['php', 'w3r', 'Python', 'abcd', 'Java', 'aaa']
# List of palindromes:
# ['php', 'aaa']

In [90]:
lis=['php', 'w3r', 'Python', 'abcd', 'Java', 'aaa']
list(filter(lambda x:x if x==x[::-1] else '',lis))

['php', 'aaa']

In [ ]:
# 19. Write a Python program to find all anagrams of a string in a given list of strings using lambda. Go to the editor
# Orginal list of strings:
# ['bcda', 'abce', 'cbda', 'cbea', 'adcb']
# Anagrams of 'abcd' in the above string:
# ['bcda', 'cbda', 'adcb']

In [95]:
from collections import Counter
lis=['bcda', 'abce', 'cbda', 'cbea', 'adcb']
list(filter(lambda x:x  if Counter(x)==Counter('abcd') else '',lis))

['bcda', 'cbda', 'adcb']

In [ ]:
# 20. Write a Python program to find the numbers of a given string and store them in a list, display the numbers which are bigger than the length of the list in sorted form. Use lambda function to solve the problem. Go to the editor
# Original string: sdf 23 safs8 5 sdfsd8 sdfs 56 21sfs 20 5
# Numbers in sorted form:
# 20 23 56

In [105]:
given_string= 'sdf 23 safs8 5 sdfsd8 sdfs 56 21sfs 20 5'
lis=[int(i) for i in given_string.split(' ') if i.isdigit()]
sorted([i for i in lis if i>len(given_string.split(' '))])

[20, 23, 56]

In [ ]:
# 21. Write a Python program that multiply each number of given list with a given number using lambda function. Print the result. Go to the editor
# Original list: [2, 4, 6, 9, 11]
# Given number: 2
# Result:
# 4 8 12 18 22

In [108]:
lis=[2, 4, 6, 9, 11]
b=int(input('Enter the number'))
result=list(map(lambda x:x*b,lis))
result

Enter the number2

[4, 8, 12, 18, 22]

In [ ]:
# 22. Write a Python program that sum the length of the names of a given list of names 
#after removing the names that starts with an lowercase letter. Use lambda function. Go to the editor
# Result:
# 16

In [115]:
sample_names = ['sally', 'Dylan', 'rebecca', 'Diana', 'Joanne', 'keith']
output=sum([len(i)  for i in sample_names if i[0].isupper()])
output

16

In [123]:
sample_names = ['sally', 'Dylan', 'rebecca', 'Diana', 'Joanne', 'keith']
output= len(''.join(list(filter(lambda x:len(x) if x[0].isupper() else '',sample_names))))
output

16

In [ ]:
# 23. Write a Python program to calculate the sum of the positive and negative numbers of a given list of numbers using lambda function. Go to the editor
# Original list: [2, 4, -6, -9, 11, -12, 14, -5, 17]
# Sum of the positive numbers: -32
# Sum of the negative numbers: 48

In [130]:
lis=[2, 4, -6, -9, 11, -12, 14, -5, 17]
positive_numbers=sum([i  for i in lis if i>0])
negative_numbers=sum([j for j  in lis if j<0])
print('positive_numbers =',positive_numbers)
print('negative_numbers =',negative_numbers)

positive_numbers = 48
negative_numbers = -32

In [138]:
lis=[2, 4, -6, -9, 11, -12, 14, -5, 17]
positive_numbers= sum(list(filter(lambda x:x  if x>0 else '',lis)))
negative_numbers=sum(list(filter(lambda x:x  if x<0 else '',lis)))
print('positive_numbers =',positive_numbers)
print('negative_numbers =',negative_numbers)

positive_numbers = 48
negative_numbers = -32

In [ ]:
# 25. Write a Python program to create the next bigger number by rearranging the digits of a given number. Go to the editor
# Original number: 12
# Next bigger number: 21
# Original number: 10
# Next bigger number: False
# Original number: 201
# Next bigger number: 210
# Original number: 102
# Next bigger number: 120
# Original number: 445
# Next bigger number: 454

In [147]:
lis=[12,10,201,102,445]
[int(str(i)[::-1]) if int(str(i)[::-1])>i else i for i in lis]

[21, 10, 201, 201, 544]

In [ ]:
# 26. Write a Python program to find the list with maximum and minimum length using lambda. Go to the editor
# Original list:
# [[0,0,0,0], [1, 3], [5, 7], [9, 11], [13, 15, 17]]
# List with maximum length of lists:
# (3, [13, 15, 17])
# List with minimum length of lists:
# (1, [0])

In [186]:
lis=[[0,0,0,0], [1, 3], [5, 7], [30, 11], [13, 15, 17]]
max_len=max(lis,key=lambda x:len(x))
length_check=max([len(i)  for i in lis])
print(f'List with maximum length of lists /n {length_check,max_len}')
min_len=min(lis,key=lambda x:len(x))
length_check_min=min([len(i)  for i in lis])
print(f'List with maximum length of lists /n {length_check_min,min_len}')

List with maximum length of lists /n (4, [0, 0, 0, 0])
List with maximum length of lists /n (2, [1, 3])

In [ ]:
# 27. Write a Python program to sort each sublist of strings in a given list of lists using lambda. Go to the editor
# Original list:
# [['green', 'orange'], ['black', 'white'], ['white', 'black', 'orange']]
# After sorting each sublist of the said list of lists:
# [['green', 'orange'], ['black', 'white'], ['black', 'orange', 'white']]

In [187]:
data=[['green', 'orange'], ['black', 'white'], ['white', 'black', 'orange']]
[sorted(i)  for i in data]

[['green', 'orange'], ['black', 'white'], ['black', 'orange', 'white']]

In [195]:
data=[['green', 'orange'], ['black', 'white'], ['white', 'black', 'orange']]
result = [sorted(x, key = lambda x:x[0]) for x in data]
result

[['green', 'orange'], ['black', 'white'], ['black', 'orange', 'white']]

In [ ]:
# 28. Write a Python program to sort a given list of lists by length and value using lambda. Go to the editor
# Original list:
# [[2], [0], [1, 3], [0, 7], [9, 11], [13, 15, 17]]
# Sort the list of lists by length and value:
9# [[0], [2], [0, 7], [1, 3], [9, 11], [13, 15, 17]]

In [228]:
lis=[[2], [0], [1, 3], [0, 7], [9, 11], [13, 15, 17]]
sorted(lis,key=lambda x:(len(x),x))

[[0], [2], [0, 7], [1, 3], [9, 11], [13, 15, 17]]

In [ ]:
# 29. Write a Python program to find the maximum value in a given heterogeneous list using lambda. Go to the editor
# Original list:
# ['Python', 3, 2, 4, 5, 'version']
# Maximum values in the said list using lambda:
# 5

In [242]:
a=['Python', 3, 2, 4, 5, 'version']
max_val = max(a, key = lambda i: (isinstance(i, int), i))  # The isinstance() function returns True if the specified object is of the specified type, otherwise False .
max_val

5

In [ ]:
# 30. Write a Python program to sort a given matrix in ascending order according to the sum of its rows using lambda. Go to the editor
# Original Matrix:
# [[1, 2, 3], [2, 4, 5], [1, 1, 1]]
# Sort the said matrix in ascending order according to the sum of its rows
# [[1, 1, 1], [1, 2, 3], [2, 4, 5]]
# Original Matrix:
# c
# Sort the said matrix in ascending order according to the sum of its rows
# [[-2, 4, -5], [1, -1, 1], [1, 2, 3]]

In [246]:
a=[[1, 2, 3], [2, 4, 5], [1, 1, 1]]
sorted(a)

[[1, 1, 1], [1, 2, 3], [2, 4, 5]]

In [249]:
data=[[1, 2, 3], [-2, 4, -5], [1, -1, 1]]
sorted(data)

[[-2, 4, -5], [1, -1, 1], [1, 2, 3]]

In [ ]:
# 31. Write a Python program to extract specified size of strings from a give list of string values using lambda. Go to the editor
# Original list:
# ['Python', 'list', 'exercises', 'practice', 'solution']
# length of the string to extract:
# 8
# After extracting strings of specified length from the said list:
# ['practice', 'solution']

In [256]:
a=['Python', 'list', 'exercises', 'practice', 'solution']
length_of_extract=int(input('Enter the length of string to extract'))
[i  for i in a  if len(i)==length_of_extract]

Enter the length of string to extract8

['practice', 'solution']

In [261]:
a=['Python', 'list', 'exercises', 'practice', 'solution']
output=list(filter(lambda x:x if len(x)==8 else '',a))
output

['practice', 'solution']

In [262]:
a=['Python', 'list', 'exercises', 'practice', 'solution']
output=list(filter(lambda x:len(x)==8,a))
output

['practice', 'solution']

In [ ]:
# 32. Write a Python program to count float number in a given mixed list using lambda. Go to the editor
# Original list:
# [1, 'abcd', 3.12, 1.2, 4, 'xyz', 5, 'pqr', 7, -5, -12.22]
# Number of floats in the said mixed list:
# 3

In [266]:
data=[1, 'abcd', 3.12, 1.2, 4, 'xyz', 5, 'pqr', 7, -5, -12.22]
len(list(filter(lambda x:isinstance(x,float),data)))

3

In [ ]:
# 34. Write a Python program to filter the height and width of students, which are stored in a dictionary using lambda. Go to the editor
# Original Dictionary:
# {'Cierra Vega': (6.2, 70), 'Alden Cantrell': (5.9, 65), 'Kierra Gentry': (6.0, 68), 'Pierre Cox': (5.8, 66)}
# Height> 6ft and Weight>= 70kg:
# {'Cierra Vega': (6.2, 70)}

In [274]:
data={'Cierra Vega': (6.2, 70), 'Alden Cantrell': (5.9, 65), 'Kierra Gentry': (6.0, 68), 'Pierre Cox': (5.8, 66)}
# Height> 6ft and Weight>= 70kg:
for i,j in data.items():
    if j[0]>6 and j[1]>=70:
        print(i,':',j)

Cierra Vega : (6.2, 70)

In [ ]:
# 35. Write a Python program to check whether a specified list is sorted or not using lambda. Go to the editor
# Original list:
# [1, 2, 4, 6, 8, 10, 12, 14, 16, 17]
# If the said list is sorted!
# True
# Original list:
# [1, 2, 4, 6, 8, 10, 12, 14, 16, 17]
# If the said list is sorted!
# False

In [276]:
nums1 = [1,2,4,6,8,10,12,14,16,17]
nums2 = [2,3,8,4,7,9,8,2,6,5,1,6,1,2,3,4,6,9,1,2]

In [282]:
def check(num1):
    if num1==sorted(num1):
        print(True)
    else:
        print(False)
        
check(nums1)
check(nums2)

True
False

In [ ]:
# 36. Write a Python program to extract the nth element from a given list of tuples using lambda. Go to the editor
# Original list:
# [('Greyson Fulton', 98, 99), ('Brady Kent', 97, 96), ('Wyatt Knott', 91, 94), ('Beau Turnbull', 94, 98)]
# Extract nth element ( n = 0 ) from the said list of tuples:
# ['Greyson Fulton', 'Brady Kent', 'Wyatt Knott', 'Beau Turnbull']
# Extract nth element ( n = 2 ) from the said list of tuples:
# [99, 96, 94, 98]

In [296]:
data=[('Greyson Fulton', 98, 99), ('Brady Kent', 97, 96), ('Wyatt Knott', 91, 94), ('Beau Turnbull', 94, 98)]
output= list(map(lambda x:(x[2]),data))
output

[99, 96, 94, 98]

In [297]:
data=[('Greyson Fulton', 98, 99), ('Brady Kent', 97, 96), ('Wyatt Knott', 91, 94), ('Beau Turnbull', 94, 98)]
[i[2] for i in data]

[99, 96, 94, 98]

In [ ]:
# 37. Write a Python program to sort a list of lists by a given index of the inner list using lambda. Go to the editor
# Original list:
# [('Greyson Fulton', 98, 99), ('Brady Kent', 97, 96), ('Wyatt Knott', 91, 94), ('Beau Turnbull', 94, 98)]
# Sort the said list of lists by a given index ( Index = 0 ) of the inner list
# [('Beau Turnbull', 94, 98), ('Brady Kent', 97, 96), ('Greyson Fulton', 98, 99), ('Wyatt Knott', 91, 94)]
# Sort the said list of lists by a given index ( Index = 2 ) of the inner list
# [('Wyatt Knott', 91, 94), ('Brady Kent', 97, 96), ('Beau Turnbull', 94, 98), ('Greyson Fulton', 98, 99)]

In [299]:
data=[('Greyson Fulton', 98, 99), ('Brady Kent', 97, 96), ('Wyatt Knott', 91, 94), ('Beau Turnbull', 94, 98)]
sorted(data,key=lambda x:x[0])

[('Beau Turnbull', 94, 98),
 ('Brady Kent', 97, 96),
 ('Greyson Fulton', 98, 99),
 ('Wyatt Knott', 91, 94)]

In [300]:
def sorting_data(a,b):
    print(sorted(a,key=lambda x:x[b]))
sorting_data(data,0)
sorting_data(data,2)

[('Beau Turnbull', 94, 98), ('Brady Kent', 97, 96), ('Greyson Fulton', 98, 99), ('Wyatt Knott', 91, 94)]
[('Wyatt Knott', 91, 94), ('Brady Kent', 97, 96), ('Beau Turnbull', 94, 98), ('Greyson Fulton', 98, 99)]

In [ ]:
# 38. Write a Python program to remove all elements from a given list present in another list using lambda. Go to the editor
# Original lists:
# list1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# list2: [2, 4, 6, 8]
# Remove all elements from 'list1' present in 'list2:
# [1, 3, 5, 7, 9, 10]

In [301]:
list1= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
list2= [2, 4, 6, 8]
output=[i  for i in list1 if i not in list2]
output

[1, 3, 5, 7, 9, 10]

In [303]:
list1= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
list2= [2, 4, 6, 8]
list(filter(lambda x:x not in list2,list1))

[1, 3, 5, 7, 9, 10]

In [ ]:
# 39. Write a Python program to find the elements of a given list of strings that contain specific substring using lambda. Go to the editor
# Original list:
# ['red', 'black', 'white', 'green', 'orange']
# Substring to search:
# ack
# Elements of the said list that contain specific substring:
# ['black']
# Substring to search:
# abc
# Elements of the said list that contain specific substring:
# []

In [304]:
lis=['red', 'black', 'white', 'green', 'orange']
[i for i in lis  if 'ack' in i]

['black']

In [ ]:
# 40. Write a Python program to find the nested lists elements, which are present in another list using lambda. Go to the editor
# Original lists: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
# [[12, 18, 23, 25, 45], [7, 11, 19, 24, 28], [1, 5, 8, 18, 15, 16]]
# Intersection of said nested lists:
# [[12], [7, 11], [1, 5, 8]]

In [310]:
data=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
check= [[12, 18, 23, 25, 45], [7, 11, 19, 24, 28], [1, 5, 8, 18, 15, 16]]
output=[j for i in check for j in i if j in data ]
output

[12, 7, 11, 1, 5, 8]

In [ ]:
# 41. Write a Python program to reverse strings in a given list of string values using lambda. Go to the editor
# Original lists:
# ['Red', 'Green', 'Blue', 'White', 'Black']
# Reverse strings of the said given list:
# ['deR', 'neerG', 'eulB', 'etihW', 'kcalB']

In [312]:
data=['Red', 'Green', 'Blue', 'White', 'Black']
list(map(lambda x:x[::-1],data))

['deR', 'neerG', 'eulB', 'etihW', 'kcalB']

In [ ]:
# 42. Write a Python program to calculate the product of a given list of numbers using lambda. Go to the editor
# list1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# Product of the said list numbers:
# 3628800
# list2: [2.2, 4.12, 6.6, 8.1, 8.3]
# Product of the said list numbers:
# 4021.8599520000007

In [316]:
from functools import reduce
list1= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(reduce(lambda x,y:x*y,list1))
list2= [2.2, 4.12, 6.6, 8.1, 8.3]
print(reduce(lambda x,y:x*y,list2))

3628800
4021.8599520000007

In [ ]:
# 43. Write a Python program to multiply all the numbers in a given list using lambda. Go to the editor
# Original list:
# [4, 3, 2, 2, -1, 18]
# Mmultiply all the numbers of the said list: -864
# Original list:
# [2, 4, 8, 8, 3, 2, 9]
# Mmultiply all the numbers of the said list: 27648

In [319]:
from functools import reduce
data=[4, 3, 2, 2, -1, 18]
print(reduce(lambda x,y:x*y,data))
data1=[2, 4, 8, 8, 3, 2, 9]
print(reduce(lambda x,y:x*y,data1))

-864
27648

In [ ]:
# 44. Write a Python program to calculate the average value of the numbers in a given tuple of tuples using lambda. Go to the editor
# Original Tuple:
# ((10, 10, 10), (30, 45, 56), (81, 80, 39), (1, 2, 3))
# Average value of the numbers of the said tuple of tuples:
# (30.5, 34.25, 27.0)
# Original Tuple:
# ((1, 1, -5), (30, -15, 56), (81, -60, -39), (-10, 2, 3))
# Average value of the numbers of the said tuple of tuples:
# (25.5, -18.0, 3.75)

In [336]:
tup=((10, 10, 10), (30, 45, 56), (81, 80, 39), (1, 2, 3))
sum([i[2] for i in tup ])/len([i[2] for i in tup ])

27.0

In [337]:
tup=((10, 10, 10), (30, 45, 56), (81, 80, 39), (1, 2, 3))
tuple(map(lambda x: sum(x) / float(len(x)), zip(*nums)))

In [ ]:
# 45. Write a Python program to convert string element to integer inside a given tuple using lambda. Go to the editor
# Original tuple values:
# (('233', 'ABCD', '33'), ('1416', 'EFGH', '55'), ('2345', 'WERT', '34'))
# New tuple values:
# ((233, 33), (1416, 55), (2345, 34))

In [341]:
data=(('233', 'ABCD', '33'), ('1416', 'EFGH', '55'), ('2345', 'WERT', '34'))
[j  for i in data for j in i if j.isdigit()]

['233', '33', '1416', '55', '2345', '34']

In [ ]:
tuple(map(lambda x: (int(x[0]), int(x[2])), tuple_str))

In [ ]:
# 46. Write a Python program to find index position and value of the maximum and minimum values in a given list of numbers using lambda. Go to the editor
# Original list:
# [12, 33, 23, 10.11, 67, 89, 45, 66.7, 23, 12, 11, 10.25, 54]
# Index position and value of the maximum value of the said list:
# (5, 89)
# Index position and value of the minimum value of the said list:
# (3, 10.11)

In [375]:
a=[12, 33, 23, 10.11, 67, 89, 45, 66.7, 23, 12, 11, 10.25, 54]
print('Index position and values of the maximum value')
print(max(enumerate(a),key=lambda x:x[1]))
print('Index position and values of the mminimum value')
print(min(enumerate(a),key=lambda x:x[1]))

Index position and values of the maximum value
(5, 89)
Index position and values of the mminimum value
(3, 10.11)

In [ ]:
# 47. Write a Python program to sort a given mixed list of integers and strings using lambda. Numbers must be sorted before strings. Go to the editor
# Original list:
# [19, 'red', 12, 'green', 'blue', 10, 'white', 'green', 1]
# Sort the said mixed list of integers and strings:
# [1, 10, 12, 19, 'blue', 'green', 'green', 'red', 'white']

In [381]:
data=[19, 'red', 12, 'green', 'blue', 10, 'white', 'green', 1]
sorted(data,key=lambda x:(isinstance(x,str),x))

[1, 10, 12, 19, 'blue', 'green', 'green', 'red', 'white']

In [380]:
data=['19', 'red', '12', 'green', 'blue', '10', 'white', 'green', '1']
sorted(data)

['1', '10', '12', '19', 'blue', 'green', 'green', 'red', 'white']

In [ ]:
# 48. Write a Python program to sort a given list of strings(numbers) numerically using lambda. Go to the editor
# Original list:
# ['4', '12', '45', '7', '0', '100', '200', '-12', '-500']
# Sort the said list of strings(numbers) numerically:
# ['-500', '-12', '0', '4', '7', '12', '45', '100', '200']

In [384]:
data=['4', '12', '45', '7', '0', '100', '200', '-12', '-500']
sorted(data,key=lambda x:int(x))

['-500', '-12', '0', '4', '7', '12', '45', '100', '200']

In [ ]:
# 49. Write a Python program to count the occurrences of the items in a given list using lambda. Go to the editor
# Original list:
# [3, 4, 5, 8, 0, 3, 8, 5, 0, 3, 1, 5, 2, 3, 4, 2]
# Count the occurrences of the items in the said list:
# {3: 4, 4: 2, 5: 3, 8: 2, 0: 2, 1: 1, 2: 2}

In [386]:
lis=[3, 4, 5, 8, 0, 3, 8, 5, 0, 3, 1, 5, 2, 3, 4, 2]
{i:lis.count(i) for i in lis}

{3: 4, 4: 2, 5: 3, 8: 2, 0: 2, 1: 1, 2: 2}

In [ ]:
# 50. Write a Python program to remove specific words from a given list using lambda. Go to the editor
# Original list:
# ['orange', 'red', 'green', 'blue', 'white', 'black']
# Remove words:
# ['orange', 'black']
# After removing the specified words from the said list:
# ['red', 'green', 'blue', 'white']

In [387]:
data=['orange', 'red', 'green', 'blue', 'white', 'black']
remove_lis=['orange', 'black']
[i  for i in data if i not in remove_lis]

['red', 'green', 'blue', 'white']

In [ ]:
# 51. Write a Python program to find the maximum and minimum values in a given list of tuples using lambda function. Go to the editor
# Original list with tuples:
# [('V', 62), ('VI', 68), ('VII', 72), ('VIII', 70), ('IX', 74), ('X', 65)]
# Maximum and minimum values of the said list of tuples:
# (74, 62)

In [391]:
data=[('V', 62), ('VI', 68), ('VII', 72), ('VIII', 70), ('IX', 74), ('X', 65)]
Maximum_number=max(data,key=lambda x:x[1])[1]
print('Maximum_number =',Maximum_number)
Minimum_number=min(data,key=lambda x:x[1])[1]
print('Minimum_number =',Minimum_number)
print(Maximum_number,Minimum_number)

Maximum_number = 74
Minimum_number = 62
74 62

In [ ]:
# 52. Write a Python program to remove None value from a given list using lambda function. Go to the editor
# Original list:
# [12, 0, None, 23, None, -55, 234, 89, None, 0, 6, -12]
# Remove None value from the said list:
# [12, 0, 23, -55, 234, 89, 0, 6, -12]

In [402]:
data=[12, 0, None, 23, None, -55, 234, 89, None, 0, 6, -12]
list(filter(lambda x:x is not None,data))

[12, 0, 23, -55, 234, 89, 0, 6, -12]

In [411]:
lis=[1,2,5,8]
lis.append(10)
lis.insert(0,25)
lis.extend((25,40,60))
lis

[25, 1, 2, 5, 8, 10, 25, 40, 60]

In [423]:
lis[0]=5

In [424]:
lis

[5, 1, 2, 5, 8, 10, 25, 40, 60]